const LANGUAGES = {
    "pt": {
        "patterns": "Padrões",
        "pause_button": "Pause",
        "run_button": "Rodar",
        "save_button": "Salvar",
        "restore_button": "Restaurar",
        "clear_button": "Limpar",
        "fps_label": "FPS: ",
        "generation_label": "Geração: ",
        "status_paused": "Pausado",
        "status_running": "Rodando",
        "status_label": "Estado: ",

        "show_qr_code_button": "Apoio Dev´s",
        "qr_code_title": "PiX caiohomemm@gmail.com",
        "close_button": "Fechar", 
        "patterns_title": "Escolha um Padrão",
        
        "live_cells_label": "Células vivas: ",
        "instructions_title": "Instruções do Jogo da Vida",
        "instructions_intro": "Bem-vindo ao Jogo da Vida de Conway!",
        "rules_title": "Regras:",
        "rule_1": "- Uma célula viva com menos de dois vizinhos vivos morre.",
        "rule_2": "- Uma célula viva com dois ou três vizinhos vivos sobrevive para a próxima geração.",
        "rule_3": "- Uma célula viva com mais de três vizinhos vivos morre.",
        "rule_4": "- Uma célula morta com exatamente três vizinhos vivos se torna uma célula viva.",
        "controls_title": "Controles:",
        "control_click": "-Clique nas células para ativá-las/desativá-las.",
        "control_toggle": "-'Rodar/Pause': Inicia/Pausa a simulação.",
        "control_save": "-'Salvar': Salva o padrão atual da grade.",
        "control_load": "-'Restaurar': Salvo ou limpa a grade se nenhum salvo.",
        "control_clear": "-'Limpar': Limpa toda a grade.",
        "control_fps_slider": "-'FPS': Ajustar a velocidade da simulação (1-60).", 
    },
    "en": {
        "patterns": "Patterns",
        "pause_button": "Pause",
        "run_button": "Run",
        "save_button": "Save",
        "restore_button": "Restore",
        "clear_button": "Clear",
        "fps_label": "FPS: ",
        "generation_label": "Generation: ",
        "status_paused": "Paused",
        "status_running": "Running",
        "status_label": "Status: ",

        "show_qr_code_button": "Show QR Code",
        "qr_code_title": "QR Code",
        "close_button": "Close", 
        "patterns_title": "Choose a Pattern",

        "live_cells_label": "Live cells: ",
        "instructions_title": "Conway's Game of Life Instructions",
        "instructions_intro": "Welcome to Conway's Game of Life!",
        "rules_title": "Rules:",
        "rule_1": "- A living cell with fewer than two living neighbours dies.",
        "rule_2": "- A living cell with two or three living neighbours lives on to the next generation.",
        "rule_3": "- A living cell with more than three living neighbours dies.",
        "rule_4": "- A dead cell with exactly three living neighbours becomes a living cell.",
        "controls_title": "Controls:",
        "control_click": "- Click on cells to toggle them.",
        "control_toggle": "-'Run/Pause': Starts/Pauses the simulation.",
        "control_save": "-'Save': Saves the current grid pattern.",
        "control_load": "-'Restore': Saved or clears the grid if none saved.",
        "control_clear": "-'Clear': Clears the entire grid.",
        "control_fps_slider": "-'FPS': Adjust simulation speed (1-60).",        
    }
};
